#pragma once

#define GCPC constexpr unsigned char
#define GCPI constexpr unsigned int

//Some constants
GCPI USERNAME_LENGTH = 16 + 1;
GCPI MESSAGE_LENGTH = 256 + 1;
GCPI GC_PROTOCOL_VERSION_LENGTH = 2;

//(If, for some reason, I go to update this project)
GCPC GC_PROTOCOL_VERSION_MAJOR = 1;
GCPC GC_PROTOCOL_VERSION_MINOR = 2;

//Defined in GESChat.cpp
int compareGCProtocolVersion(unsigned char major, unsigned char minor);

//Initial codes
GCPC HANDSHAKE = 0x01;
GCPC SENDING_MESSAGE = 0x02;
GCPC BROADCASTING_MESSAGE = 0x03;
GCPC SERVER_TECHNICAL_BROADCASTING = 0x04;
GCPC FORWARDING_PRIVATE_MESSAGE = 0x05;

//Packets' lengths
GCPI HANDSHAKE_LENGTH_CS = 1 + GC_PROTOCOL_VERSION_LENGTH + USERNAME_LENGTH;
GCPI HANDSHAKE_LENGTH_SC = 1 + 1 + GC_PROTOCOL_VERSION_LENGTH;
GCPI SENDING_MESSAGE_LENGTH = 1 + MESSAGE_LENGTH;
GCPI BROADCASTING_MESSAGE_LENGTH = 1 + USERNAME_LENGTH + MESSAGE_LENGTH;
GCPI SERVER_TECHNICAL_BROADCASTING_LENGTH = 1 + 1 + USERNAME_LENGTH;
GCPI FORWARDING_PRIVATE_MESSAGE_LENGTH = 1 + 1 + USERNAME_LENGTH + USERNAME_LENGTH + MESSAGE_LENGTH;

#define MAX_SERVER_POSSIBLE_INPUT 512
#define MAX_CLIENT_POSSIBLE_INPUT 512

//Techincal Broadcasting:
GCPC SERVER_TECHNICAL_BROADCASTING_STATUS_USER_JOINED = 0x20;
GCPC SERVER_TECHNICAL_BROADCASTING_STATUS_USER_LEFT = 0x21;

//Private message statuses
GCPC FORWARDING_PRIVATE_MESSAGE_STATUS_OK = 0x10;
GCPC FORWARDING_PRIVATE_MESSAGE_STATUS_USER_NOT_FOUND = 0x11;

//Server errors
GCPC INVALID_DATA = 0x30;

GCPC SERVER_OK = 0x40;
GCPC SERVER_ERROR_INCOMPATABLE_PROTOCOL_VERSION = 0x41;
GCPC SERVER_ERROR_TRANSCENDED_BACKLOG = 0x42;
GCPC SERVER_ERROR_DUPLICATE_USERNAME = 0x43;
GCPC SERVER_ERROR_INVALID_USERNAME = 0x44;
